// Auto-generated by tools/generate_luts.py — DO NOT EDIT
#pragma once

#include <stdint.h>
#include "lut_custom_1_cine4_clearwater.h"
#include "lut_custom_1_cine4_donner.h"
#include "lut_custom_1_cine4_freel.h"
#include "lut_custom_1_cine4_grieves.h"
#include "lut_custom_1_cine4_humphreys.h"
#include "lut_custom_1_cine4_jobs.h"
#include "lut_custom_1_cine4_maggies.h"
#include "lut_custom_1_cine4_mt_rose.h"
#include "lut_custom_1_cine4_orion_tempe_2.h"
#include "lut_custom_1_cine4_orion_tempe.h"
#include "lut_custom_1_cine4_rubicon.h"
#include "lut_custom_1_cine4_spooner.h"
#include "lut_custom_baltimore.h"
#include "lut_custom_dover.h"
#include "lut_custom_fuji_classic_neg_by_seim_1_1.h"
#include "lut_custom_fuji_pro_400_cin.h"
#include "lut_custom_fuji_pro_400_fc.h"
#include "lut_custom_fuji_pro_400_fpe.h"
#include "lut_custom_fuji_pro_400_vs.h"
#include "lut_custom_fuji_superior_200_cin.h"
#include "lut_custom_fuji_superior_200_fc.h"
#include "lut_custom_fuji_superior_200_fpe.h"
#include "lut_custom_fuji_superior_200_vs.h"
#include "lut_custom_fujicolor_200_cin.h"
#include "lut_custom_fujicolor_200_fc.h"
#include "lut_custom_fujicolor_200_fpe.h"
#include "lut_custom_fujicolor_200_vs.h"
#include "lut_custom_hartford.h"
#include "lut_custom_juneau.h"
#include "lut_custom_kodak_ektar_100_cin.h"

struct CustomLutEntry {
    const char* name;
    const uint16_t* lut;
};

static const CustomLutEntry CUSTOM_LUTS[] = {
    {"1 Cine4 Clearwater", LUT_CUSTOM_1_CINE4_CLEARWATER},
    {"1 Cine4 Donner", LUT_CUSTOM_1_CINE4_DONNER},
    {"1 Cine4 Freel", LUT_CUSTOM_1_CINE4_FREEL},
    {"1 Cine4 Grieves", LUT_CUSTOM_1_CINE4_GRIEVES},
    {"1 Cine4 Humphreys", LUT_CUSTOM_1_CINE4_HUMPHREYS},
    {"1 Cine4 Jobs", LUT_CUSTOM_1_CINE4_JOBS},
    {"1 Cine4 Maggies", LUT_CUSTOM_1_CINE4_MAGGIES},
    {"1 Cine4 Mt.Rose", LUT_CUSTOM_1_CINE4_MT_ROSE},
    {"1 Cine4 Orion Tempe 2", LUT_CUSTOM_1_CINE4_ORION_TEMPE_2},
    {"1 Cine4 Orion Tempe", LUT_CUSTOM_1_CINE4_ORION_TEMPE},
    {"1 Cine4 Rubicon", LUT_CUSTOM_1_CINE4_RUBICON},
    {"1 Cine4 Spooner", LUT_CUSTOM_1_CINE4_SPOONER},
    {"Baltimore", LUT_CUSTOM_BALTIMORE},
    {"Dover", LUT_CUSTOM_DOVER},
    {"Fuji Classic Neg by Seim 1.1", LUT_CUSTOM_FUJI_CLASSIC_NEG_BY_SEIM_1_1},
    {"Fuji Pro 400_CIN", LUT_CUSTOM_FUJI_PRO_400_CIN},
    {"Fuji Pro 400_FC", LUT_CUSTOM_FUJI_PRO_400_FC},
    {"Fuji Pro 400_FPE", LUT_CUSTOM_FUJI_PRO_400_FPE},
    {"Fuji Pro 400_VS", LUT_CUSTOM_FUJI_PRO_400_VS},
    {"Fuji Superior 200_CIN", LUT_CUSTOM_FUJI_SUPERIOR_200_CIN},
    {"Fuji Superior 200_FC", LUT_CUSTOM_FUJI_SUPERIOR_200_FC},
    {"Fuji Superior 200_FPE", LUT_CUSTOM_FUJI_SUPERIOR_200_FPE},
    {"Fuji Superior 200_VS", LUT_CUSTOM_FUJI_SUPERIOR_200_VS},
    {"FujiColor 200_CIN", LUT_CUSTOM_FUJICOLOR_200_CIN},
    {"FujiColor 200_FC", LUT_CUSTOM_FUJICOLOR_200_FC},
    {"FujiColor 200_FPE", LUT_CUSTOM_FUJICOLOR_200_FPE},
    {"FujiColor 200_VS", LUT_CUSTOM_FUJICOLOR_200_VS},
    {"Hartford", LUT_CUSTOM_HARTFORD},
    {"Juneau", LUT_CUSTOM_JUNEAU},
    {"Kodak Ektar 100_CIN", LUT_CUSTOM_KODAK_EKTAR_100_CIN},
};

static const int CUSTOM_LUT_COUNT = 30;
